#!/bin/bash

for file in $( ls outputs/* ); do
   echo -n "Testing with ${file} -- "

   BASE=`basename ${file} .out`

   # program testing
   \./hdecode ${file} doutputs/${BASE}.out
 
   #make expected
   \cat ${file} > dexpected/${BASE}.expect

   # compare results
   diff doutputs/${BASE}.out dexpected/${BASE}.expect &> doutputs/${BASE}.diff

   if [ $? -eq 0 ]; then
      echo "Succeeded"

      # comment out these lines to retain output and diff files
      \rm outputs/${BASE}.out
      \rm outputs/${BASE}.diff
   else
      #echo "Failed"
      echo -n "Testing with ${file} -- "	
      #echo "   See differences in outputs/${BASE}.diff"
   fi
done
